version: "3.1"
services:
    mysql:
        image: mysql:8.0
        container_name: survey-mysql
        volumes:
            - ./data/mysql:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=survey_app
            - MYSQL_USER=survey
            - MYSQL_PASSWORD=survey
        ports:
            - "8001:3306"
